(function($){var
props=['Width','Height'],prop;while(prop=props.pop()){(function(natural,prop){$.fn[natural]=(natural in new Image())?function(){return this[0][natural]}:function(){var
node=this[0],img,value;if(node.tagName.toLowerCase()==='img'){img=new Image();img.src=node.src,value=img[prop]}
return value}}('natural'+prop,prop.toLowerCase()))}}(jQuery));jQuery.fn.center=function(){this.css("position","absolute");this.css("top",Math.max(0,100+$(window).scrollTop())+"px");this.css("left",Math.max(0,(($(window).width()-$(this).outerWidth())/2)+$(window).scrollLeft())+"px");return this}
if($('.filter').length){filter_fly_offset=$('.filter').offset().top-20;$(document).scroll(function(){offset=$('#sidebar').innerHeight();h=$('.filter').innerWidth();if((filter_fly_offset+h+offset)<$(this).scrollTop()){$('#fly-block').addClass('flying');$(".flying").stick_in_parent({offset_top:10,parent:'.place'})}else{$('#fly-block').removeClass('flying is_stuck');$("#fly-block").trigger("sticky_kit:detach")}})}
$(document).ready(function(){sub_menu_timer='';$('.sub_menu > a:nth-of-type(1)').on('mouseover',function(){$('.hover_cat_menu').hide(100);clearInterval(sub_menu_timer);sub_menu_timer=setInterval(function(){$('.hover_cat_menu.hcm_goods').hide(0);$('.hover_cat_menu.hcm_producers').show(200);clearInterval(sub_menu_timer)},500)})
$('.sub_menu > a:nth-of-type(2)').on('mouseover',function(e){$('.hover_cat_menu').hide(100);clearInterval(sub_menu_timer);sub_menu_timer=setInterval(function(){$('.hover_cat_menu.hcm_producers').hide(0);$('.hover_cat_menu.hcm_goods').show(200);clearInterval(sub_menu_timer)},500)})
$('.sub_menu > a:nth-of-type(1), .sub_menu > a:nth-of-type(2)').on('mouseleave',function(){clearInterval(sub_menu_timer)})
$('.hover_cat_menu, .sub_menu').on('mouseleave',function(){$('.hover_cat_menu').hide(100)})
$('.hndl_activate_orders_show_contacts').on('click',function(e){overlay_show();$.post('/ajax/orders_show_contacts',function(data){if(data=='1'){alert('Услуга успешно подключена.');window.location.reload()}else{alert('Недостаточно средств. Пополните счет и повторите попытку.')}
overlay_hide()});e.preventDefault()});$('.hndl_is_can_add_product').on('click',function(e){overlay_show();producer_id=$(this).data('producer-id');if(producer_id.length<=0||producer_id=='0')return!0;$.post('/ajax/is_can_add_product',{producer_id:producer_id},function(data){data=$.parseJSON(data);if(data=='1'){window.location.href='/products/add';return}
if(!$('.mod_window.additional_product').length){$('body').append(data);$('.mod_window.additional_product span.close').click(function(e){$('.mod_window').css({'opacity':'1','margin-top':'50px'});$('.mod_window').delay(300).hide(0);e.preventDefault()});$('.hndl_activate_additional_product').on('click',function(e){overlay_show();$.post('/ajax/paid_service_activate',{service_id:13},function(data){if(data=='1'){alert('Услуга успешно подключена.');window.location.href='/products/add'}else if(data=='2'){alert('На вашем счете недостаточно средств. Пополните баланс.')}
overlay_hide()});e.preventDefault()})}
$('.mod_window.additional_product').show(0).css({'opacity':'1','margin-top':'-50px'});overlay_hide()});e.preventDefault()})
$('#srch').autocomplete({serviceUrl:'/ajax/get_search_suggestions',type:'POST',dataType:'json',minChars:3,onSelect:function(suggestion){window.location.href=suggestion.data},formatResult:function(suggestion,currentValue){return'<a data-id="'+suggestion.id+'" href="'+suggestion.data+'">'+suggestion.value+'</a>'}});$('#light-srch').autocomplete({serviceUrl:'/ajax/get_search_suggestions',type:'POST',dataType:'json',minChars:3,appendTo:$('#top_bar section form'),position:'relative',formatResult:function(suggestion,currentValue){return'<a data-id="'+suggestion.id+'" href="'+suggestion.data+'">'+suggestion.value+'</a>'}});$(".chosen-select").chosen();$(".fancybox").fancybox({beforeShow:function(){var alt=this.element.find('img').attr('alt');this.inner.find('img').attr('alt',alt);this.title=alt}});$(".fancybox-video").fancybox({type:'iframe'});$(".slides").jCarouselLite({btnNext:"#popular .next",btnPrev:"#popular .prev"});window.page_loading=!1;if(isNaN(window.page))
window.page=1;$('#try-load-again a, #next_page').bind('click',function(){load_page();$('#try-load-again a, .pagination').hide();$('.loader').show();return!1});$('.comments').on('click','a.p_reply',function(e){comment_id=$(this).data('comment-id');type=$(this).data('item-type');elem=$('#comment_answer_reply').show();$('#comment-'+comment_id).after(elem);elem.find('input[name="parent_id"]').val(comment_id);elem.find('input[name="type"]').val(type)});$('.comments .comment i.plus').on('click',function(){comment_rate($(this),1)});$('.comments .comment i.minus').on('click',function(){comment_rate($(this),-1)});$('#items_regions, #items_rubrics, #firms_regions').hide()
$('.catalog .sort a').click(function(){var tab_id=$(this).data('rel');$('.catalog .sort a').removeClass('active');$('.columns').hide();$(this).addClass('active');$("#"+tab_id).fadeTo(720,1).show()});$('#load-comments').on('click',function(e){if(typeof(window.comments_page)=="undefined"){window.comments_page=1}
$(this).addClass('submit');window.comments_page ++;$id=$(this).data('item-id');$type=$(this).data('item-type');$page=window.comments_page;$.post('/ajax/load_comments',{page:$page,id:$id,type:$type},function(data){data=$.parseJSON(data);$('.preloader').before(data);$('.preloader > a').removeClass('submit');if(data.length<50)$('.preloader').remove()})});$('.sc_list').click(function(){$(this).toggleClass("show").toggleClass("hide").next().slideToggle(240)});$('#center, .big_map').on('mouseover','.item_images .img_check i',function(){offset=$(this).closest('.img_list').outerWidth();index=$(this).index()*(-1)*offset;$(this).closest('div.img_list').find('> div').css('left',index)});$('#center, .big_map').on('mouseleave','.item_images',function(){$(this).find('.img_list > div').css('left','0')});$('.view_space').on('mouseover','.mi_images .img_check i',function(){index=$(this).index()*-240;$(this).closest('div.img_list').find('> div').css('left',index)});$('.view_space').on('mouseleave','.mi_images',function(){$(this).find('.img_list > div').css('left','0')});$('.items .img_check, .map_card .img_check').each(function(){if($(this).find('i').length<2){$(this).find('i').css('position','static')}});if($('.img_check a')){$('.view_space').on('mouseover','.items .img_check a',function(){count=$(this).parent().find('a').length;index=$(this).index();left_value=-140*index;scroller=$(this).closest('.item').find('.img_list > div');scroller.animate({left:left_value},140,'swing')});$('#center').on('click','.items  .img_check a',function(event){event.preventDefault()})}
$('a.ask_me').click(function(){$('#post_area').focus();setTimeout(function(){$('#post_area').focus()},10)});$('.post .btn.publish').click(function(e){window.overlay_lock=!0;overlay_show();params=$(this).closest('form').serialize();window.parent_id=parseInt($(this).parent().find('input[name="parent_id"]').val());type_id=parseInt($(this).parent().find('input[name="type"]').val());comments_div=$(this).closest("div.comments");$.post('/ajax/post_comment',params,function(data){if(data=='err_1'){alert('Вы не указали контактных данных')}else if(data=='category_err'){alert('Выберите категорию.')}else if(data.length>10){data=$.parseJSON(data);if(window.parent_id>0){$('#comment-'+window.parent_id).after(data)}else{if(type_id==6){alert(data.message);window.location.reload()}else{comments_div.prepend(data);alert('Сообщение отправлено, если производитель не ответит Вам в течении суток — свяжитесь с ним по телефону во вкладке «Контакты»')}}
$('.post.new').show(0).queue(function(){$('html, body').animate({scrollTop:($(this).offset().top-20)},320);$(this).animate({opacity:'1'},2000)
$(this).dequeue();$(this).queue(function(){$(this).removeClass('new');$(this).dequeue()})});$('.post.add_form textarea[name="content"]').val('')}
window.overlay_lock=!1;overlay_hide()});e.preventDefault()});$('.p_text > textarea').keydown(function(){$(this).next('div.pt_water').animate({opacity:'hide'},160)});$('div.pt_water').click(function(){$(this).animate({opacity:'hide'},160);$(this).parent().find('textarea').focus()});$(window).scroll(function(){if($(this).scrollTop()!=0){$('#to_top').fadeIn()}else{$('#to_top').fadeOut()}});$('#to_top').click(function(){$('body,html').animate({scrollTop:0},800)});$(window).scroll(function(){if($(this).scrollTop()>=300){$('#top_bar').fadeIn(540)}else{$('#top_bar').fadeOut(820)}});$('#top_bar .tb_up').click(function(){$('body,html').animate({scrollTop:0},800)});$('.annonce > .close').click(function(){$('.annonce').animate({opacity:'hide'},420)});$('.cs_rating .cs_btn, .ps_rating .ps_btn').click(function(){$(this).toggleClass('active');$('.cs_extra.go_pay, .ps_extra.go_pay').fadeOut(90);$('.cs_balance .cs_btn, .ps_balance .ps_btn').removeClass('active');$('.cs_extra.about_rating, .ps_extra.about_rating').slideToggle(210)});$('.cs_balance .cs_btn, .ps_balance .ps_btn').click(function(){$(this).toggleClass('active');$('.cs_extra.about_rating, .ps_extra.about_rating').fadeOut(90);$('.cs_rating .cs_btn, .ps_rating .ps_btn').removeClass('active');$('.cs_extra.go_pay, .ps_extra.go_pay').slideToggle(210)});$('a#order-button').click(function(){$('#overlay').fadeIn(420);$('.place').css('z-index','auto');$('.order_form').show(240).animate({left:'-=370px',opacity:'1'},240);$('.order_form').find('input:first-child').focus();window.yaCounter156713.reachGoal('order_btn')});$('#send-order').click(function(e){$('.order_form > form').delay(200).hide(0);params=$('.order_form > form').serialize();if($('.order_form > form input[name="name"]').val().length<=0){$('.order_form > form input[name="name"]').addClass('error');e.preventDefault();return!1}
if($('.order_form > form input[name="email"]').val().length<=0){$('.order_form > form input[name="email"]').addClass('error');e.preventDefault();return!1}
if($('#order-item textarea[name="details"]').val().length<=0){$('#order-item textarea[name="details"]').addClass('error');e.preventDefault();return!1}
if(!$('#privacy-policy').prop("checked")){alert('Для отправки заказа производителю с Выставки необходимо согласие с политикой конфиденциальности.');return!1}
$.post('/ajax/order',params,function(data){window.yaCounter156713.reachGoal('order_submit');window.yaCounter156713.reachGoal('order_submit_a')});$('.inform').delay(200).show(0).animate({opacity:'1'},500);$('#send-order-again').click(function(){$('.inform').delay(200).hide(0);$('.order_form > form').delay(200).show(0)})});$('#send-order-2').click(function(e){$('#order-item input, #order-item textarea').removeClass('error');params=$('#order-item').serialize();if($('#order-item input[name="name"]').val().length<=0){$('#order-item input[name="name"]').addClass('error');e.preventDefault();return!1}
if($('#order-item input[name="email"]').val().length<=0){$('#order-item input[name="email"]').addClass('error');e.preventDefault();return!1}
if($('#order-item textarea[name="details"]').val().length<=0){$('#order-item textarea[name="details"]').addClass('error');e.preventDefault();return!1}
if(!$('#privacy-policy').prop("checked")){alert('Для отправки заказа производителю с Выставки необходимо согласие с политикой конфиденциальности.');return!1}
$.post('/ajax/order',params,function(data){window.yaCounter156713.reachGoal('order_submit');window.yaCounter156713.reachGoal('order_submit_b')});$('#order-item').hide(0);$('.inform').show(200).animate({opacity:'1'},500);e.preventDefault();return!1});$('#send-order-3').click(function(e){$('#order-item > span.ob_info red').hide();$('#order-item input, #order-item textarea').removeClass('error');params=$('#order-item').serialize();if($('#order-item input[name="name"]').val().length<=0){$('#order-item input[name="name"]').addClass('error');$('#order-item > span.ob_info red').show();e.preventDefault();return!1}
if($('#order-item input[name="email"]').val().length<=0){$('#order-item input[name="email"]').addClass('error');$('#order-item > span.ob_info red').show();e.preventDefault();return!1}
if($('#order-item textarea[name="details"]').val().length<=0){$('#order-item textarea[name="details"]').addClass('error');e.preventDefault();return!1}
if(!$('#privacy-policy').prop("checked")){alert('Для отправки заказа производителю с Выставки необходимо согласие с политикой конфиденциальности.');return!1}
$.post('/ajax/order',params,function(data){window.yaCounter156713.reachGoal('order_submit');window.yaCounter156713.reachGoal('order_submit_b_company')});$('#order-item').hide(0);$('.inform').show(200).animate({opacity:'1'},500);e.preventDefault();return!1});$('.order_form span.close, #overlay').click(function(){$('.order_form').animate({left:'+=370px',opacity:'0'},500).hide(10);if(!window.overlay_lock)
$('#overlay').fadeOut(500);$('.place').css('z-index','10');$('.order_form > form').delay(500).show(0);$('.inform').delay(500).hide(0)});$('#footer').on('click','.f_share a.b-share__handle',function(){url=encodeURI(window.location.href);var imageUrl='';switch($(this).attr('class')){case 'od':openWindow('http://www.odnoklassniki.ru/dk?st.cmd=addShare&st.s=0&st._surl='+url);break;case 'tw':openWindow('http://twitter.com/share?url='+url);break;case 'gp':openWindow('http://connect.mail.ru/share');break;case 'vk':var vkUrl='http://vk.com/share.php?url='+url;if(imageUrl){vkUrl+='&image='+imageUrl}
openWindow(vkUrl);break;case 'fb':var fbUrl='http://www.facebook.com/sharer.php?u='+url;openWindow(fbUrl);break}
$.post("/ajax/shared");return!1});$('.like-image-block > a').on('click',function(){url=encodeURI(window.location.href);var imageUrl=$(this).parent().data('image');imageUrl=encodeURI(imageUrl);switch($(this).attr('class')){case 'od':openWindow('https://www.odnoklassniki.ru/dk?st.cmd=addShare&st.s=0&st._surl='+url);break;case 'tw':openWindow('https://twitter.com/share?url='+url);break;case 'gp':openWindow('https://connect.mail.ru/share?url='+url);break;case 'vk':var vkUrl='https://vk.com/share.php?url='+url;if(imageUrl){vkUrl+='&image='+imageUrl}
openWindow(vkUrl);break;case 'fb':var fbUrl='https://www.facebook.com/sharer.php?p[url]='+url;openWindow(fbUrl);break}
$.post("/ajax/shared");window.yaCounter156713.reachGoal('photo-like');return!1});$('.hndl_show_contacts').on('click',function(e){$('.popup_window').show(0).css({'opacity':'1'});e.preventDefault()});$('.hndl_show_statmodal').click(function(e){$('.mod_window').show(0).css({'opacity':'1','margin-top':'-50px'});e.preventDefault()});$('.mod_window span.close').click(function(e){$('.mod_window').css({'opacity':'1','margin-top':'50px'});$('.mod_window').delay(300).hide(0);e.preventDefault()});$(".popup_window span.close").click(function(e){$(".popup_window").delay(300).hide(0),e.preventDefault()})
$('.hndl_activate_statistics').on('click',function(e){overlay_show();$.post('/ajax/paid_service_activate',{service_id:5},function(data){if(data=='1'){alert('Услуга успешно подключена.');window.location.href='/privateoffice/statistic/'}else if(data=='2'){alert('На вашем счете недостаточно средств. Пополните баланс.')}
overlay_hide()});e.preventDefault()})});function openWindow($url){var leftvar=(screen.width-700)/2;var topvar=(screen.height-450)/2;var viewer=window.open($url,'','menubar=no,location=no,resizable=no,scrollbars=no,status=no,width=700,height=450,left='+leftvar+',top='+topvar);viewer.focus()}
function load_page(){page_loading=!0;window.page++;if(typeof window.paginator_version_2=='boolean'){$.get(window.location.href,{ajax:1,page:window.page},function(data){data=JSON.parse(data);if(data.items.length){$('.loader').before(data.items);$('.items .img_check, .map_card .img_check').each(function(){if($(this).find('i').length<2){$(this).find('i').css('position','static')}});window.page_loading=!1;$('#next_page').parent().show()}else{window.smart_scroll==!1;if(window.see_also_trigger){see_also()}}
$('.pagination > .page_links').replaceWith(data.pagination)
$('.loader').hide()}).fail(function(){window.page_loading=!1;$('.pagination').show();$('.loader').hide();$('#next_page').hide()})}else{$.get(window.location.href,{ajax:1,page:window.page},function(data){if(data.length>20){$('.loader').before(data);$('.items .img_check, .map_card .img_check').each(function(){if($(this).find('i').length<2){$(this).find('i').css('position','static')}});window.page_loading=!1;$('#next_page').parent().show()}else{window.smart_scroll==!1;if(window.see_also_trigger){see_also()}}
$('.loader').hide()}).fail(function(){window.page_loading=!1})}}
function ajaxAvatarUpload(){overlay_show();jQuery.ajaxFileUpload({url:'/ajax/avatar_load',secureuri:!1,fileElementId:'fileToUpload',dataType:'json',success:function(data,status){if(typeof(data.error)!='undefined'){if(data.error!=''){alert(data.error)}else{$('.avatar-upload div').html('<img src="'+data.file+'" />');$('.avatar-upload p').remove();$('.hndl_avatar_delete').show()}}
overlay_hide()},error:function(data,status,e){alert(e);overlay_hide()}})
return!1}
function ajaxNewsUpload(){overlay_show();jQuery.ajaxFileUpload({url:'/upload-photo/',secureuri:!1,fileElementId:'fileToUpload2',dataType:'json',success:function(data,status){if(typeof(data.error)!='undefined'){if(data.error!=''){alert(data.error)}else{$('.avatar-upload div').html('<img src="'+data.file+'" /><input type="hidden" name="photo" value="'+data.file_id+'" />');$('.avatar-upload p').remove()}}
overlay_hide()},error:function(data,status,e){alert(e);overlay_hide()}})
return!1}
function ajaxConsultantUpload(){overlay_show();jQuery.ajaxFileUpload({url:'/ajax/consultant_load',secureuri:!1,type:'POST',fileElementId:'fileToUpload',dataType:'json',success:function(data,status){if(typeof(data.error)!='undefined'){if(data.error!=''){alert(data.error)}else{$('#customization .zone > img').load(function(){y_2=parseInt($('#customization .zone > img').height());x_2=parseInt($('#customization .zone > img').width());console.log(x_2);console.log(y_2);offset_x=0;offset_y=0;if(y_2>x_2){offset_y=(y_2-x_2)/2;y_2=x_2+offset_y;console.log('oy:'+offset_y)}else{offset_x=(x_2-y_2-1)/2;x_2=y_2+offset_x;console.log('OX:'+offset_x)}
$('#customization .zone > img').imgAreaSelect({aspectRatio:'1:1',handles:!0,x1:offset_x,y1:offset_y,x2:x_2,y2:y_2,onSelectEnd:function(img,selection){scale=$('#customization .zone > img').naturalWidth()/$('#customization .zone > img').width();$('#photoload input[name="x1"]').val(selection.x1);$('#photoload input[name="x2"]').val(selection.x2);$('#photoload input[name="y1"]').val(selection.y1);$('#photoload input[name="y2"]').val(selection.y2);$('#photoload input[name="scale"]').val(scale)},onInit:function(img,selection){scale=$('#customization .zone > img').naturalWidth()/$('#customization .zone > img').width();$('#photoload input[name="x1"]').val(selection.x1);$('#photoload input[name="x2"]').val(selection.x2);$('#photoload input[name="y1"]').val(selection.y1);$('#photoload input[name="y2"]').val(selection.y2);$('#photoload input[name="scale"]').val(scale)},});$(this).unbind('load')});$('#customization .zone').parent().show();$('#customization .zone > img').attr('src',data.file)}}
overlay_hide()},error:function(data,status,e){alert(e);overlay_hide()}})
return!1}
function photoUploader_load_by_url(id){result=jQuery(id).val();if(result){jQuery("#photo_loading").show();overlay_show();descr=jQuery('#photo-description').val();jQuery.post('/upload-photo/',{type:'url',url:result,description:descr},function(data_request){data=jQuery.parseJSON(data_request);if(typeof(data.error)!='undefined'){if(data.error!=''){alert(data.error)}else{html='<div class="g_upload_item"><div><img src="/photos/small/'+data.file+'" alt=""></div><input type="text" name="photo_description[]" placeholder="Укажите название"><input type="hidden" value="'+data.file_id+'" name="photo[]"></div>';$('#add_img').append(html);jQuery('#photo-url').val('')}}
$('#loaded').show();jQuery("#photo_loading").hide();overlay_hide()})}else{alert('Сначала введите URL (ссылку) на изображение')}
return!1}
window.overlay_lock=!1;function overlay_show(){$('#overlay').show(80)}
function overlay_hide(){if(!window.overlay_lock)
overlay_hide_force()}
function overlay_hide_force(){$('#overlay').hide(30)}
function set_main_img(obj,img){jQuery('#add_img img').removeClass('thumbnail-selected');obj.addClass('thumbnail-selected');jQuery('#main_photo').val(img)}
function remove_img(obj){if(obj.next().hasClass('thumbnail-selected')){jQuery('#main_photo').val('')}
id=obj.next().val();$.post('/ajax/remove_image',{id:id});obj.parent().remove();return!1}
jQuery.extend({handleError:function(s,xhr,status,e){if(s.error)
s.error(xhr,status,e);else if(xhr.responseText)
console.log(xhr.responseText)}});function ajaxFileUpload(){count_photos=$('div.upload.images > div').length-1;if(count_photos>=30){alert('Не более 30 фотографий на одну экспозицию.');return!1}
jQuery("#photo_loading").show();jQuery.ajaxFileUpload({url:'/upload-photo/',secureuri:!1,fileElementId:'fileToUpload',dataType:'json',beforeSend:function(){jQuery("#photo_loading").show()},complete:function(){jQuery("#photo_loading").hide()},success:function(data,status){if(typeof(data.error)!='undefined'){if(data.error!=''){alert(data.error)}else{title='Обложка';if(typeof(window.photos_replace_text)!='undefined')title='Логотип';$html='<div>'+'  <a href="#"><img src="'+data.file+'"></a>'+'  <input type="text" placeholder="Описание..." name="photo_description[]">'+'  <span class="cover_img">'+'      <label><input type="radio" name="obl"  onclick="javascript: set_main_img(jQuery(this), \''+data.file+'\');">&nbsp;'+title+'</label>'+'  </span>'+'  <span class="close" title="Удалить"  onclick="javascript: remove_img(jQuery(this));">×</span>'+'<input type="hidden" value="'+data.file_id+'" name="photo[]">'+'</div>';jQuery('#photo_loading').before($html);if(jQuery('#add_img').children().size()==1){jQuery('#add_img li input[name="condition"]').attr('checked','checked');jQuery('#main_photo').val(data.file_id)}}}},error:function(data,status,e){alert(e)}})
return!1}
function photoUploader_load_by_url(id){count_photos=$('div.upload.images > div').length-1;if(count_photos>=30){alert('Не более 30 фотографий на одну экспозицию.');return!1}
result=jQuery(id).val();if(result){jQuery("#photo_loading").show();descr=jQuery('#photo-description').val();jQuery.post('/upload-photo/',{type:'url',url:result,description:descr},function(data_request){data=jQuery.parseJSON(data_request);if(typeof(data.error)!='undefined'){if(data.error!=''){alert(data.error)}else{title='Обложка';if(typeof(window.photos_replace_text)!='undefined')title='Логотип';$html='<div>'+'  <a href="#"><img src="'+data.file+'"></a>'+'  <input type="text" placeholder="Описание..." name="photo_description[]">'+'  <span class="cover_img">'+'      <label><input type="radio" name="obl" onclick="javascript: set_main_img(jQuery(this), \''+data.file_id+'\');">&nbsp;'+title+'</label>'+'  </span>'+'  <span class="close" title="Удалить"  onclick="javascript: remove_img(jQuery(this));">×</span>'+'<input type="hidden" value="'+data.file_id+'" name="photo[]">'+'</div>';jQuery('#photo_loading').before($html);if(jQuery('#add_img').children().size()==1){jQuery('#add_img li input[name="condition"]').attr('checked','checked');jQuery('#main_photo').val(data.file_id)}
jQuery('#photo-url').val('')}}
jQuery("#photo_loading").hide()})}else{alert('Сначала введите URL (ссылку) на изображение')}
return!1}
$('#upload-video').on('click',function(event){event.preventDefault();video_url=$('#video-url').val();if(video_url.length<5){alert('Введите корректную ссылку на ролик в YouTube.');return!1}
var myregexp=/(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/ ]{11})/i;var videoID=video_url.match(myregexp);videoID=videoID[1];html='<div>'+'  <a target="_blank" href="http://www.youtube.com/watch?v='+videoID+'">'+'  <i class="video">&nbsp;</i>'+'  <img src="http://i2.ytimg.com/vi/'+videoID+'/hqdefault.jpg" alt="">'+'  </a>'+'  <span class="close" title="Удалить"  onclick="javascript: remove_img(jQuery(this));">×</span>'+'  <input type="hidden" value="'+videoID+'" name="video[]">'+'</div>';jQuery('#video_loading').before(html);$('#video-url').val('');return!1});function ajaxFilesUpload(file_type){if(file_type=='price')file_type='price-list';jQuery("#files_loading").show();jQuery.ajaxFileUpload({url:'/upload-file/',secureuri:!1,fileElementId:'filesToUpload',dataType:'json',beforeSend:function(){jQuery("#files_loading").show()},complete:function(){jQuery("#files_loading").hide()},success:function(data,status){if(typeof(data.error)!='undefined'){if(data.error!=''){alert(data.error)}else{$html='<a href="/uploads/'+data.id+'/" class="download '+file_type+'">'+'  <i>&nbsp;</i>'+'  <span>'+data.name+'</span>'+'  <small>'+data.size+'</small>'+'  <span class="close" title="Удалить" onclick="javascript: remove_img(jQuery(this)); return false;">×</span>'+'  <input type="hidden" value="'+data.id+'" name="files[]"> '+'  <input type="hidden" value="'+data.name+'" name="files_name[]"> '+'  <input type="hidden" value="'+data.size+'" name="files_size[]"> '+'  <input type="hidden" value="'+file_type+'" name="files_type[]"> '+'</a>';jQuery('#files_loading').before($html)}}},error:function(data,status,e){alert(e)}})
return!1}
function comment_rate(elem,vote){id=elem.closest('.comment').data('comment-id');$.post('/ajax/comment_rate',{comment_id:id,value:vote},function(data){e=elem.closest('div.comment').find('.score');e.html(data);if(data<0){e.removeClass('good').addClass('bad')}else{e.removeClass('bad').addClass('good')}})}
function insertTextAtCursor(el,text,offset){var val=el.value,endIndex,range,doc=el.ownerDocument;if(typeof el.selectionStart=="number"&&typeof el.selectionEnd=="number"){endIndex=el.selectionEnd;el.value=val.slice(0,endIndex)+text+val.slice(endIndex);el.selectionStart=el.selectionEnd=endIndex+text.length+(offset?offset:0)}else if(doc.selection!="undefined"&&doc.selection.createRange){el.focus();range=doc.selection.createRange();range.collapse(!1);range.text=text;range.select()}}